use techshop;
-- Task 3. Aggregate functions, Having, Order By, GroupBy and Joins:
-- 1. Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order.
select * from orders;
select o.orderid,o.customerid,concat(c.firstname,' ',c.lastname) as customername from orders o inner join customers c on o.customerid=c.customerid;
-- 2. Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue.
select * from products;

-- 3. Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information.
select o.orderid,c.customerid,concat(c.Firstname,' ',c.lastname) as customername,c.email,c.phone,c.address 
from orders o 
inner join customers c on o.customerid=c.customerid 
group by c.customerid,c.firstname,c.lastname,c.email,c.phone,c.address;

-- 4. Write an SQL queryorderdetails to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered.
select * from orderdetails;
select productid ,max(quantity) as maxquantity from orderdetails group by productid order by maxquantity desc limit 1;
-- 5. Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
alter table products add category varchar(40);
UPDATE products
SET category = 'portable electronics'
WHERE productname LIKE '%phone%' OR
      productname LIKE '%laptop%' OR
      productname LIKE '%tablet%';
select * from products;
UPDATE products
SET category = 'output device'
WHERE productname LIKE '%monitor%' OR
      productname LIKE '%printer%' OR
      productname LIKE '%speaker%';
select * from products;
UPDATE products
SET category = 'input device'
WHERE productname LIKE '%mouse%' OR
      productname LIKE '%keyboard%';
select * from products;
UPDATE products
SET category = 'computer parts'
WHERE productname LIKE '%harddrive%' OR
      productname LIKE '%router%';
select * from products;
select productname,category from products;
-- 6. Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value.
select o.customerid,avg(o.totalamount) as averageordervalue,concat(c.Firstname,' ',c.Lastname) as customername from orders o inner join customers c on o.customerid=c.customerid group by o.customerid;
-- 7. Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue.
select o.orderid,concat(c.firstname,' ',c.lastname),sum( from orders;
8. Write an SQL query to list electronic gadgets and the number of times each product has been 
ordered.
9. Write an SQL query to find customers who have purchased a specific electronic gadget product. 
Allow users to input the product name as a parameter.
10. Write an SQL query to calculate the total revenue generated by all orders placed within a 
specific time period. Allow users to input the start and end dates as parameters.